//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FstyleLotteryXamarin.Strings {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FstyleLotteryXamarin.Strings.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AboutString {
            get {
                return ResourceManager.GetString("AboutString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F-Style Lottery に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Publisher に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear Elected Items に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ClearElectedItemsAppBarButton {
            get {
                return ResourceManager.GetString("ClearElectedItemsAppBarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Lottery Items に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditItemsAppBarButton {
            get {
                return ResourceManager.GetString("EditItemsAppBarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last loterry number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LastLotteryNumber {
            get {
                return ResourceManager.GetString("LastLotteryNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Include Elected Items に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LegendModeAppBarButton {
            get {
                return ResourceManager.GetString("LegendModeAppBarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Beverages に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LotteryItem1 {
            get {
                return ResourceManager.GetString("LotteryItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Condiments に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LotteryItem2 {
            get {
                return ResourceManager.GetString("LotteryItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jams, Preserves に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LotteryItem3 {
            get {
                return ResourceManager.GetString("LotteryItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dried Fruit &amp; Nuts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LotteryItem4 {
            get {
                return ResourceManager.GetString("LotteryItem4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Canned Fruit &amp; Vegetables に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LotteryItem5 {
            get {
                return ResourceManager.GetString("LotteryItem5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Baked Goods &amp; Mixes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LotteryItem6 {
            get {
                return ResourceManager.GetString("LotteryItem6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Canned Meat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LotteryItem7 {
            get {
                return ResourceManager.GetString("LotteryItem7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Navigation failed! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NavigationFailedExceptionMessage {
            get {
                return ResourceManager.GetString("NavigationFailedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Numbers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NumbersTabHeader {
            get {
                return ResourceManager.GetString("NumbersTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Lottery Items に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switch back to fullscreen to play. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SnapViewMessage {
            get {
                return ResourceManager.GetString("SnapViewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sorting order of numbers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SortingOrder {
            get {
                return ResourceManager.GetString("SortingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ascending に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SortingOrderOffContent {
            get {
                return ResourceManager.GetString("SortingOrderOffContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Random に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SortingOrderOnContent {
            get {
                return ResourceManager.GetString("SortingOrderOnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The sound files this application uses given on 01SoundEarth. Those sound files licensed under a Creative Commons License. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SoundFilesAgreementText {
            get {
                return ResourceManager.GetString("SoundFilesAgreementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Free Sound Material 01SoundEarth に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SoundFilesAgreementTitle {
            get {
                return ResourceManager.GetString("SoundFilesAgreementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartButton {
            get {
                return ResourceManager.GetString("StartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StopButton {
            get {
                return ResourceManager.GetString("StopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextTabHeader {
            get {
                return ResourceManager.GetString("TextTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F-Style Lottery に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UiAppName {
            get {
                return ResourceManager.GetString("UiAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
